import {places,freshState,restore,edges,neighbors,view,move,anchor} from './engine.js';
const $=id=>document.getElementById(id), key='cache-city-v1';
let s;try{s=restore(localStorage.getItem(key));}catch{s=freshState();}
let selected=null;
const coords={home:[150,120],tower:[360,100],bakery:[495,255],bridge:[320,345],garden:[105,290],yard:[535,90]};
const ns='http://www.w3.org/2000/svg';
function svg(tag,attrs,text){const n=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;return n;}
function button(text,fn){const b=document.createElement('button');b.textContent=text;b.onclick=fn;return b;}
function save(){try{localStorage.setItem(key,JSON.stringify(s));$('save-state').textContent='行程已保存在本机';$('save-state').classList.remove('save-error');}catch{$('save-state').textContent='无法存档，本次仍可游玩';$('save-state').classList.add('save-error');}}
function go(id){if(!move(s,id))return;closeEditor();save();render();$('scene').classList.remove('scene-change');void $('scene').offsetWidth;$('scene').classList.add('scene-change');$('place-name').setAttribute('tabindex','-1');$('place-name').focus({preventScroll:true});if(matchMedia('(max-width:650px)').matches)$('scene').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});}
function renderMap(){const m=$('map');m.replaceChildren();m.append(svg('path',{d:'M 215 410 C 255 315 230 220 300 190 S 445 200 420 25',class:'map-water'}),svg('path',{d:'M 215 410 C 255 315 230 220 300 190 S 445 200 420 25',class:'map-water-edge'}));for(const [a,b]of edges(s)){const [x1,y1]=coords[a],[x2,y2]=coords[b];m.append(svg('path',{d:`M ${x1} ${y1} L ${x2} ${y2}`,class:`road ${b==='yard'?'new':''}`}));}m.append(svg('text',{x:25,y:425,class:'map-caption'},'城 市 暂 存 图'));
for(const [id,[x,y]]of Object.entries(coords)){if(id==='yard'&&s.stages.tower<2)continue;const v=view(s,id),can=neighbors(s).includes(id),current=id===s.at;const g=svg('g',{transform:`translate(${x} ${y})`,class:`map-node ${current?'current':''} ${can?'available':''}`,role:'button',tabindex:can?'0':'-1','aria-label':`${v.name}${current?'，你在这里':can?'，前往此处':'，需要经由相邻地点前往'}`,'aria-disabled':String(!can)});g.append(svg('circle',{r:22,fill:'transparent',opacity:0}),svg('circle',{r:current?9:6}));if(v.anchor)g.append(svg('circle',{cx:16,cy:-12,r:4,class:'anchor-marker'}));if(v.stage)g.append(svg('text',{y:-21,class:'old-name'},places[id].names[0]));g.append(svg('text',{y:34},v.name),svg('text',{y:54,class:'map-state'},current?'你在这里':can?'可前往':s.seen.includes(id)?'曾经到访':'未到访'));if(can){g.onclick=()=>go(id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go(id);}};}m.append(g);}}
function render(){const v=view(s);$('condition').textContent=['此刻清晰','含义开始漂移','旧事留下了痕迹'][v.stage];$('place-count').textContent=`已到访 ${s.seen.length} / 6`; $('place-name').textContent=v.name;$('story').textContent=v.body;$('trace').textContent=s.stages[s.at]?v.trace:'停下来读一会儿，这里不会因此遗忘。';$('saved-quote').hidden=!v.anchor;$('saved-quote').replaceChildren();if(v.anchor){const label=document.createElement('small');label.textContent='留下的文字';$('saved-quote').append(label,document.createTextNode(`“${v.anchor.text}”`));}$('steps').textContent=`行走 ${s.turns} 步`;$('anchor-count').textContent=`已用 ${s.anchors.length} / 2 个锚点`;$('slot-count').textContent=`${s.anchors.length} / 2`;$('write-anchor').textContent=v.anchor?'改写这里的锚言':'在这里留下锚言';$('exits').replaceChildren(...neighbors(s).map(id=>{const b=button(view(s,id).name,()=>go(id));const icon=svg('svg',{viewBox:'0 0 20 20','aria-hidden':'true'});icon.append(svg('path',{d:'M3 10h13m-5-5 5 5-5 5',fill:'none',stroke:'currentColor','stroke-width':1.3}));b.append(icon);return b;}));$('anchors').replaceChildren();if(!s.anchors.length){const p=document.createElement('p');p.className='empty';p.textContent='还没有留下文字。先走走，再决定什么值得记住。';$('anchors').append(p);}for(const a of s.anchors){const row=document.createElement('div');row.className='anchor-entry';const name=document.createElement('span');name.textContent=view(s,a.id).name;const q=document.createElement('q');q.textContent=a.text;row.append(name,q);$('anchors').append(row);}$('journal').replaceChildren(...s.log.slice(0,4).map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));$('mission').replaceChildren();if(s.at==='home'&&s.seen.includes('tower')){if(!s.reported)$('mission').append(button('把钟楼的见闻带回来',()=>{s.reported=true;save();render();}));else{const p=document.createElement('p');p.textContent='你把见闻留在门边。纸条背面慢慢浮出一句话：“谢谢你回来。时间变了也没关系。”这一段委托结束了，城市仍然可以继续探索。';$('mission').append(p);}}renderMap();}
function closeEditor(){$('anchor-editor').hidden=true;$('replacement').hidden=true;selected=null;$('write-anchor').setAttribute('aria-expanded','false');}
function commit(replace){if(anchor(s,selected,replace)){closeEditor();save();render();$('announcement').textContent='锚言已留下。文字会保留，含义仍可能变化。';$('write-anchor').focus();}}
$('write-anchor').onclick=()=>{const open=$('anchor-editor').hidden;$('anchor-editor').hidden=!open;$('write-anchor').setAttribute('aria-expanded',String(open));$('replacement').hidden=true;if(!open)return;$('choices').replaceChildren(...places[s.at].choices.map(text=>{const b=button(`“${text}”`,()=>{selected=text;if(s.anchors.length>=2&&!s.anchors.some(a=>a.id===s.at)){for(const child of $('choices').children)child.setAttribute('aria-pressed',String(child===b));$('replacement').hidden=false;$('replace-choices').replaceChildren(...s.anchors.map(a=>button(`${view(s,a.id).name} · ${a.text}`,()=>commit(a.id))));}else commit();});b.setAttribute('aria-pressed','false');return b;}));$('choices').firstChild.focus();};
$('cancel-anchor').onclick=()=>{closeEditor();$('write-anchor').focus();};$('help-toggle').onclick=()=>{$('help').hidden=!$('help').hidden;$('help-toggle').setAttribute('aria-expanded',String(!$('help').hidden));};$('restart').onclick=()=>$('reset-dialog').showModal();$('cancel-reset').onclick=()=>$('reset-dialog').close();$('confirm-reset').onclick=()=>{s=freshState();closeEditor();save();render();$('reset-dialog').close();};render();
