import {chromium} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('.impeccable/review',{recursive:true});
await page.goto('http://127.0.0.1:4187');
await page.screenshot({path:'.impeccable/review/desktop.png',fullPage:true});
await page.locator('#exits button').filter({hasText:'钟楼'}).click();
await page.locator('#write-anchor').click();
await page.locator('#choices button').filter({hasText:'3:17。'}).click();
assert.match(await page.locator('#saved-quote').textContent(),/3:17/);
await page.reload();assert.equal(await page.locator('#place-name').textContent(),'钟楼');
await page.locator('#exits button').filter({hasText:'白房间'}).click();
await page.locator('#mission button').click();assert.match(await page.locator('#mission').textContent(),/谢谢你回来/);
await page.locator('#write-anchor').click();await page.locator('#choices button').first().click();
await page.locator('#exits button').filter({hasText:'花园'}).click();
await page.locator('#write-anchor').click();await page.locator('#choices button').first().click();
assert.equal(await page.locator('#replacement').isVisible(),true);
await page.locator('#replace-choices button').first().click();
assert.equal(await page.locator('.anchor-entry').count(),2);
await page.locator('#restart').click();await page.locator('#cancel-reset').click();assert.equal(await page.locator('.anchor-entry').count(),2);
await page.locator('#restart').click();await page.locator('#confirm-reset').click();assert.equal(await page.locator('.anchor-entry').count(),0);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.impeccable/review/mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#exits button').filter({hasText:'钟楼'}).click();assert.equal(await page.locator('#place-name').textContent(),'钟楼');
assert.equal(await page.evaluate(()=>document.fonts.check('18px "City Serif"')),true);
await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('storage blocked');};});
await page.locator('#exits button').first().click();
assert.equal(await page.locator('#save-state').isVisible(),true);
await page.screenshot({path:'.impeccable/review/mobile-save-error.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('Browser checks passed: movement, anchor, reload, quest, replacement, restart, mobile overflow, no page errors.');
await browser.close();
