const { chromium } = require(process.env.SYNTAX_PLAYWRIGHT_MODULE || '../../protocol-zoo/node_modules/@playwright/test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '..');
const output = path.join(root, '.impeccable', 'review');

(async () => {
  await fs.mkdir(output, { recursive: true });
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', acceptDownloads: true });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await page.goto(pathToFileURL(path.join(root, 'index.html')).href);
    await page.evaluate(() => localStorage.clear());
    await page.reload();
    assert.equal(await page.title(), '句法小径 · 把一句话走一遍');
    assert.equal(await page.locator('#previous').isDisabled(), true);
    const walk = async expected => {
      for (const place of expected) {
        await page.locator('#next').click();
        assert.equal(await page.locator('#place-title').textContent(), place);
        assert.match(await page.locator('#bead').getAttribute('transform'), /^translate\([\d.]+ [\d.]+\)$/);
      }
    };
    await walk(['看见了', '共用门厅', '学生的']);
    assert.equal(await page.locator('.door-leaf.open').count(), 1);
    await walk(['回到共用门厅', '老师', '连接平台', '朋友', '一句话，走完了']);
    await page.locator('#note').fill('A：在共用门厅回望。');
    await page.locator('#naturalness').selectOption('自然');
    await page.locator('#next').click();
    assert.equal(await page.locator('[data-model="B"]').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('#note').inputValue(), '');
    await walk(['看见了', '经过门槛', '老师', '学生的', '回到老师房间', '连接平台', '朋友', '一句话，走完了']);
    await page.locator('#previous').click();
    assert.equal(await page.locator('#place-title').textContent(), '朋友');
    await page.locator('#note').fill('B：只接老师。<script>原样保留</script>');
    await page.locator('#naturalness').selectOption('需要上下文');
    await page.locator('[data-note="A"]').click();
    assert.equal(await page.locator('#note').inputValue(), 'A：在共用门厅回望。');
    await page.reload();
    assert.equal(await page.locator('#note').inputValue(), 'A：在共用门厅回望。');
    await page.locator('[data-note="B"]').click();
    assert.equal(await page.locator('#naturalness').inputValue(), '需要上下文');
    await page.locator('#note').focus();
    const before = await page.locator('#step-count').textContent();
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#step-count').textContent(), before);
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#export').click();
    const download = await downloadPromise;
    const downloadText = await fs.readFile(await download.path(), 'utf8');
    assert.match(downloadText, /A：在共用门厅回望。/);
    assert.match(downloadText, /B：只接老师。<script>原样保留<\/script>/);
    assert.equal(downloadText.match(/屏幕路径：已走完/g).length, 2);
    const folded = await page.locator('.room-top').first().getAttribute('d');
    await page.locator('#fold').uncheck();
    assert.notEqual(await page.locator('.room-top').first().getAttribute('d'), folded);
    await page.locator('#hide-labels').check();
    assert.equal(await page.locator('.room-text').first().evaluate(el => getComputedStyle(el).visibility), 'hidden');
    await page.locator('#hide-labels').uncheck();
    await page.locator('#fold').check();
    await page.locator('[data-model="B"]').click();
    await walk(['看见了', '经过门槛', '老师', '学生的']);
    assert.equal(await page.locator('.outside-scope').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(251, 249, 243)');
    await page.locator('#note').fill('');
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: path.join(output, 'desktop-side.png'), fullPage: true });
    await page.locator('[data-model="A"]').click();
    await page.locator('#note').fill('');
    const overflow = [];
    for (const width of [1440, 768, 390, 320]) {
      await page.setViewportSize({ width, height: width > 600 ? 1000 : 844 });
      await page.evaluate(async () => { await document.fonts.ready; window.scrollTo(0, 0); });
      const overflowing = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
      const sceneBounds = await page.locator('#scene').boundingBox();
      assert.ok(sceneBounds.height > 200, `Scene has no usable height at ${width}`);
      overflow.push({ width, overflowing });
      assert.equal(overflowing, false, `Overflow at ${width}`);
      if (width === 1440 || width === 390) await page.screenshot({ path: path.join(output, width === 1440 ? 'desktop.png' : 'mobile.png'), fullPage: true });
    }
    await page.locator('#next').focus(); await page.keyboard.press('Enter');
    assert.equal(await page.locator('#place-title').textContent(), '看见了');
    await page.evaluate(() => document.activeElement.blur());
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#place-title').textContent(), '共用门厅');
    await page.keyboard.press('ArrowLeft');
    assert.equal(await page.locator('#place-title').textContent(), '看见了');
    await page.locator('#restart').click();
    assert.equal(await page.locator('#place-title').textContent(), '入口庭院');
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.locator('#next').click();
    assert.equal(await page.locator('#next').isDisabled(), true);
    await page.waitForFunction(() => !document.querySelector('#next').disabled);
    assert.equal(await page.locator('#place-title').textContent(), '看见了');
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.evaluate(() => localStorage.setItem('syntax-path-notes-v1', '{broken'));
    await page.reload();
    assert.match(await page.locator('#save-status').textContent(), /无法读取/);
    await page.locator('#note').fill('损坏存档后也可以重新记录。');
    assert.match(await page.locator('#save-status').textContent(), /已保存/);
    const isolated = await browser.newContext({ reducedMotion: 'reduce' });
    await isolated.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage blocked'); } }); });
    const blocked = await isolated.newPage();
    await blocked.goto(pathToFileURL(path.join(root, 'index.html')).href);
    await blocked.locator('#note').fill('不能保存，也能试玩。');
    assert.match(await blocked.locator('#save-status').textContent(), /无法自动保存/);
    await blocked.locator('#next').click();
    assert.equal(await blocked.locator('#place-title').textContent(), '看见了');
    await isolated.close();
    assert.deepEqual(errors, []);
    const result = { routes: 'A and B, side-room return, restart and switching', notes: 'independent persistence, ratings, export, corrupt and blocked storage', inputs: 'mouse, touch-size viewports, keyboard, fold and labels', overflow, errors };
    await fs.writeFile(path.join(output, 'verification.json'), JSON.stringify(result, null, 2));
    console.log(JSON.stringify(result, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
