const { chromium, expect } = require('@playwright/test');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  fs.mkdirSync(path.join(__dirname, '../test-results'), { recursive: true });
  await page.clock.install();
  await page.goto(pathToFileURL(path.join(__dirname, '../index.html')).href);
  await expect(page.locator('#status')).toHaveText('已连接');
  await page.screenshot({ path: 'test-results/desktop-empty.png', fullPage: true });
  const send = async bytes => { await page.locator(`[data-byte="${bytes}"]`).click(); await page.clock.runFor(350); };
  await page.locator('#bytes').fill('G1'); await page.locator('#send').click();
  await expect(page.locator('#input-error')).toContainText('十六进制');
  for (const bytes of ['11', '22', '11', '22']) await send(bytes);
  await page.clock.runFor(1200);
  await expect(page.locator('.proactive code')).toHaveText('11');
  await page.locator('[data-byte="33"]').click();
  await page.clock.runFor(500);
  await expect(page.locator('#send')).toBeDisabled();
  await page.clock.runFor(600);
  await expect(page.locator('.rx code').last()).toHaveText('00');
  await page.locator('#notes').fill('交替发送后，它先发出了 11。改变为 33 后，收到 00。');
  await page.screenshot({ path: 'test-results/desktop-interaction.png', fullPage: true });
  await page.locator('#rest').click(); await expect(page.locator('#status')).toHaveText('休息中');
  await page.clock.runFor(5000);
  await page.locator('#rest').click(); await page.clock.runFor(1000);
  await expect(page.locator('.rx').filter({ hasText: '重连信号' })).toHaveCount(2);
  await page.locator('[data-byte="FF"]').click(); await page.locator('#pause').click();
  const count = await page.locator('.rx').count(); await page.clock.runFor(5000);
  await expect(page.locator('.rx')).toHaveCount(count);
  await page.locator('#pause').click(); await page.clock.runFor(1100);
  await expect(page.locator('.rx')).toHaveCount(count + 1);
  // Rest must cancel an in-flight response and reconnect must not replay it.
  await page.locator('[data-byte="33"]').click(); await page.locator('#rest').click();
  const restingCount = await page.locator('.rx').count(); await page.clock.runFor(3000);
  await expect(page.locator('.rx')).toHaveCount(restingCount);
  await page.locator('#rest').click(); await page.clock.runFor(1000);
  const downloadPromise = page.waitForEvent('download'); await page.locator('#export').click();
  const download = await downloadPromise; await download.saveAs('test-results/export.txt');
  expect(fs.readFileSync('test-results/export.txt', 'utf8')).toContain('交替发送后');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  await page.locator('#reset').click(); await page.locator('button[value="cancel"]').click();
  await expect(page.locator('#notes')).not.toHaveValue('');
  await page.locator('#reset').click(); await page.locator('button[value="reset"]').click();
  await expect(page.locator('#notes')).toHaveValue(''); await expect(page.locator('.rx')).toHaveCount(0);
  await expect(page.locator('#session-number')).toHaveText('002');
  await page.clock.runFor(5000); await expect(page.locator('.rx')).toHaveCount(0);
  await page.locator('#rest').click(); await page.locator('#rest').click(); await page.clock.runFor(1500);
  await expect(page.locator('.rx')).toHaveCount(0);
  expect(errors).toEqual([]);
  await browser.close(); console.log('PASS: browser interaction, timers, export, reset, and responsive widths 320/390/768/1440; no page errors.');
})().catch(error => { console.error(error); process.exit(1); });
